backend:
  name: git-gateway
  branch: main

site_url: https://civicwatch.it
display_url: https://civicwatch.it
logo_url: https://civicwatch.it/favicon.svg

media_folder: "public/uploads"
public_folder: "/uploads"

publish_mode: editorial_workflow

collections:
  - name: "pagine"
    label: "Pagine"
    label_singular: "Pagina"
    folder: "content/pages"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Titolo", name: "title", widget: "string" }
      - { label: "Slug (url)", name: "slug", widget: "string", hint: "es. chi-siamo" }
      - { label: "Sintesi", name: "summary", widget: "text", required: false }
      - { label: "Corpo", name: "body", widget: "markdown" }

  - name: "news"
    label: "News & Avvisi"
    label_singular: "Notizia"
    folder: "content/news"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Titolo", name: "title", widget: "string" }
      - { label: "Data", name: "date", widget: "datetime" }
      - { label: "Categoria", name: "category", widget: "select", options: ["Avviso", "Comunicato", "Evento"] }
      - { label: "Immagine di copertina", name: "cover", widget: "image", required: false }
      - { label: "Corpo", name: "body", widget: "markdown" }

  - name: "impostazioni"
    label: "Impostazioni Sito"
    delete: false
    editor:
      preview: false
    files:
      - file: "src/site.json"
        name: "site"
        label: "Configurazione"
        fields:
          - { label: "Nome sito", name: "site_name", widget: "string", default: "Civic Watch" }
          - { label: "Titolo Hero", name: "hero_title", widget: "string", default: "Segnala. Risolvi. Migliora la città." }
          - { label: "Sottotitolo Hero", name: "hero_subtitle", widget: "text", default: "Un canale diretto tra cittadini e Comune per segnalazioni rapide." }
          - { label: "Testo pulsante CTA", name: "cta_label", widget: "string", default: "Invia Segnalazione" }
